# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-build

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
      - stable/*
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master
      - stable/*

# Explicitly disable secrets.GITHUB_TOKEN permissions.
permissions: {}

jobs:
  build:
    # NOTE: This name appears in GitHub's Checks API.
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Set workflow variables
        # Id is needed to access output in a next step.
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build web ROSE Wallet
        run: yarn build
      - name: Build extension ROSE Wallet
        run: yarn build:ext
      - name: Sync Capacitor for Android
        run: yarn cap sync android
      - name: Accept SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Install SDK components
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
      - name: Build Android ROSE Wallet
        run: ./gradlew bundleRelease
        working-directory: android
      - name: Upload Android ROSE Wallet build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: rose-wallet-android-${{ steps.vars.outputs.SHORT_SHA }}.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
      - name: Upload web ROSE Wallet build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: rose-wallet-web-${{ steps.vars.outputs.SHORT_SHA }}
          path: build
      - name: Upload extension ROSE Wallet build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: rose-wallet-ext-${{ steps.vars.outputs.SHORT_SHA }}
          path: build-ext
