name: Stage Deploy

on:
  workflow_dispatch:
    inputs:
      walletBackend:
        type: choice
        description: 'Wallet Backend'
        options:
          - build:oasisscan
          - build:oasismonitor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn ${{ github.event.inputs.walletBackend }}
      - uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
      - name: Deploy to AWS S3
        run: |
          aws s3 sync --delete --acl public-read --cache-control 'max-age=2592000' . s3://${{ secrets.AWS_S3_BUCKET }}
          aws s3 website s3://${{ secrets.AWS_S3_BUCKET }} --index-document index.html --error-document index.html
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUD_FRONT_DISTRIBUTION }} --paths "/*"
